<Project Sdk="Microsoft.NET.Sdk.Web">
 

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-givPayroll-aaeb190b-090c-4744-9bc4-fd6cb3a90dc1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\NewFolder\**" />
    <Compile Remove="wwwroot\images\Personnel - Copy\**" />
    <Content Remove="wwwroot\images\NewFolder\**" />
    <Content Remove="wwwroot\images\Personnel - Copy\**" />
    <EmbeddedResource Remove="wwwroot\images\NewFolder\**" />
    <EmbeddedResource Remove="wwwroot\images\Personnel - Copy\**" />
    <None Remove="wwwroot\images\NewFolder\**" />
    <None Remove="wwwroot\images\Personnel - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NCalc" Version="7.1.0" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageReference Include="SQLitePCLRaw.core" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="wwwroot\images\Personnel\" />
    <Folder Include="wwwroot\pages\js\" />
  </ItemGroup>

</Project>
